const colors = {
  light: {
    text: "#1e293b",
    tint: "#6366f1",
    background: "#f8fafc",
    foreground: "#1e293b",
    card: "#ffffff",
    cardForeground: "#1e293b",
    primary: "#6366f1",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#1e293b",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#ede9fe",
    accentForeground: "#4338ca",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    success: "#22c55e",
    warning: "#f59e0b",

    // tool badge colors
    toolSummarize: "#dbeafe",
    toolSummarizeFg: "#1d4ed8",
    toolLinkedin: "#ede9fe",
    toolLinkedinFg: "#6d28d9",
    toolEmail: "#dcfce7",
    toolEmailFg: "#15803d",
    toolSearch: "#ffedd5",
    toolSearchFg: "#c2410c",
    toolDocqa: "#fce7f3",
    toolDocqaFg: "#9d174d",
    toolDefault: "#f1f5f9",
    toolDefaultFg: "#475569",
  },
  radius: 12,
};

export default colors;
